### ISSUE TITLE
Please use this as a reference for overall theme look and feel

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#10]
http://demo.themewagon.com/preview/boxer-software-landing-page-free-html5-template

**Comment by Danial-Pervaiz** [comment]
oaky got it

**Comment by campustradein** [comment]
Here is the home page mockup I came up with: 
[hompage_mockup.pdf](https://github.com/campustradein/front-end/files/317351/hompage_mockup.pdf)
