### ISSUE TITLE
Signup form validation

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#18]
- [ ] username should be 3 characters or more but at most 10 characters
- [ ] password should be 8 characters or more
- [ ] add confirm password field (if it doesnt match let them know)
- [ ] email should be valid (e.g something@email.com)
- [ ] Don't allow signup if the forms are invalid
- [ ] When username is valid, make a rest api call to "" to check if the username is taken or not. The api returns 200 OK if valid. If username is taken, a 4XX code is returned. 
- [ ] Display a green checkmark within the form if username and email is valid and checked against the server
- [x] Use formvalidation.io

**Comment by Danial-Pervaiz** [comment]
(When username is valid, make a rest api call to "" to check if the username is taken or not. The api returns 200 OK if valid. If username is taken, a 4XX code is returned)
(Display a green checkmark within the form if username and email is valid and checked against the server)

**Comment by Danial-Pervaiz** [comment]
i need database in the backend to check the username and email if existed or not. and unfortunately i can't work with backend technologies

**Comment by campustradein** [comment]
For checking email: http://www.campustradein.com/signup/formok&email=someone@me.com
For checking username: http://www.campustradein.com/signup/formok&username=someone

**Comment by Danial-Pervaiz** [comment]
its showing jumbotron like this in my laptop. do you still want it short
