### ISSUE TITLE
signup and login should be EXACTLY similar to the one on coursera.org

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#2]
![image](https://cloud.githubusercontent.com/assets/19155331/16083650/674d3ea8-32db-11e6-8f6f-f1838b63d819.png)

Fields for signup:
- [x] username
- [x] email
- [x] password
- [ ] select university
  Rather than having a checkbox to accept terms and condition, just display a message, just like coursera

**Comment by Danial-Pervaiz** [comment]
completed
