### ISSUE TITLE
create account activation page

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#23]

**Comment by Danial-Pervaiz** [comment]
you want the seprate page or just the pop up?

**Comment by campustradein** [comment]
I think a separate page since the user will click on the link from an email and the server will redirect he/she to the homepage. Not sure if I can call a modal dialog from the server. Or is there a way to programmatically display a popup when the user gets redirected to the homepage?

**Comment by Danial-Pervaiz** [comment]
please check the page. and let me know what exact changes you want in this page.
