### ISSUE TITLE
make video section full-width 

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#25]
<img width="871" alt="screen shot 2016-06-18 at 5 55 31 pm" src="https://cloud.githubusercontent.com/assets/19155331/16174198/e5998d80-357d-11e6-9c2c-ccbb7da6ce87.png">

Button should say see how it works

**Comment by Danial-Pervaiz** [comment]
which image should i use behind this video button.

**Comment by campustradein** [comment]
Use the flyer. The one that says buy textbooks fast and easy. Thanks

**Comment by Danial-Pervaiz** [comment]
im closing this issue. video section is completed. you just have to put BG image
