### ISSUE TITLE
Use Roboto font for the jumbotron (exactly the way it looks on current site). no upper case

### ISSUE THREAD

**Issue by campustradein** [campustradein/front-end#3]
The shade of blue should also be exactly the same as the current site's shade of blue

**Comment by Danial-Pervaiz** [comment]
Completed

**Comment by campustradein** [comment]
Please all fonts needs to Roboto. The font you're using looks like times new romans
![image](https://cloud.githubusercontent.com/assets/19155331/16120733/305769e8-33a6-11e6-9a99-74d8478dbb9a.png)

**Comment by Danial-Pervaiz** [comment]
please check the roboto font. i changed the campustradein name together without caps
